apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: getlogs
    docker:
      dockerfile: ./monitoring/getlogs/Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - ./monitoring/getlogs/k8s-*
profiles:
- name: incluster
  build:
    artifacts:
    - image: getlogs
      kaniko:
        dockerfile: ./monitoring/getlogs/Dockerfile
        buildContext:
          localDir: {}
        cache:
          repo: 'DEFAULT_REPO/monitoring-getlogs-cache'
    cluster:
      pullSecretName: stub
      namespace: default
      dockerConfig:
        secretName: docker-config-secret-in-kubernetes