apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-1
  labels:
    folder: api
spec:
  template:
    spec:
      imagepullsecrets:
      - name: regcred
      containers:
      - image: api
        env:
        - name: token
          valueFrom:
            secretKeyRef:
              name: token
              key: token-webservice-1
